# Generated by Django 5.1.2 on 2024-10-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_details_facebook_details_github_details_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='lname',
            field=models.CharField(default=' ', max_length=60),
        ),
    ]
