# Generated by Django 5.1.2 on 2024-10-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_details_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="details",
            name="images",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="profile-photo/"
            ),
        ),
    ]
